# Project
projectGroup=com.yogieat
projectVersion=0.0.1

# Gradle performance
org.gradle.parallel=true
org.gradle.caching=true

# Plugin Versions
springBootVersion=3.5.9
springDependencyManagementVersion=1.1.7
spotlessVersion=7.0.2

# Dependency Versions
googleGenaiVersion=1.10.0
hibernateVersion=6.6.10.Final
springdocVersion=2.8.5
querydslVersion=7.1
jjwtVersion=0.12.6
