apply plugin: 'com.google.cloud.tools.jib'

dependencies {
    implementation project(':apps:domain')
    implementation project(':storage:db-core')
    implementation project(':external:kakao')
    implementation project(':external:ai')
    implementation project(':support:logging')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
}

tasks.named('bootJar') {
    enabled = true
}

tasks.named('jar') {
    enabled = false
}

def dockerHubUsername = System.getenv('DOCKERHUB_USERNAME')
def dockerHubToken = System.getenv('DOCKERHUB_TOKEN')

jib {
    from {
        image = 'amazoncorretto:25-alpine-jdk'
    }
    to {
        image = System.getenv('BATCH_IMAGE_FULL_URL') ?: 'yogieat/yogieat-server-batch-sync:local'
        if (dockerHubUsername && dockerHubToken) {
            auth {
                username = dockerHubUsername
                password = dockerHubToken
            }
        }
    }
    containerizingMode = 'exploded'
    container {
        mainClass = 'com.yogieat.SyncBatchApplication'
        environment = [TZ: 'Asia/Seoul']
    }
}
