spring:
  threads:
    virtual:
      enabled: true
  application:
    name: yogieat
  config:
    import:
      - logging.yaml
      - datasource.yaml
      - monitoring.yaml
      - ai.yaml
      - client.yaml
      - swagger.yaml
  web.resources.add-mappings: false
  task:
    scheduling:
      enabled: true

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

sync:
  job:
    chunk-size: 50
    parallelism: 4
    poll-delay-ms: 5000
    weekly-cron: "0 0 21 ? * SUN"
    weekly-zone: "Asia/Seoul"
