spring:
  threads:
    virtual:
      enabled: true
  application:
    name: yogieat
  config:
    import:
      - logging.yaml
      - datasource.yaml
      - monitoring.yaml
      - ai.yaml
      - client.yaml
      - swagger.yaml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
