spring:
  threads:
    virtual:
      enabled: true
  application:
    name: yogieat
  config:
    import:
      - logging.yaml
      - datasource.yaml
      - monitoring.yaml
      - ai.yaml
      - client.yaml
      - swagger.yaml
  web.resources.add-mappings: false
  task:
    scheduling:
      enabled: true

server:
  tomcat:
    max-connections: 20000
    threads:
      max: ${API_TOMCAT_MAX_THREADS:180}
      min-spare: ${API_TOMCAT_MIN_THREADS:20}

sync:
  job:
    chunk-size: 50
    parallelism: 4
    poll-delay-ms: 5000
    weekly-cron: "0 0 21 ? * SUN"
    weekly-zone: "Asia/Seoul"

kakao:
  client:
    enabled: ${KAKAO_CLIENT_ENABLED:true}
  api:
    client:
      enabled: ${kakao.client.enabled}
