services:
  yogieat-api:
    image: ${API_IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_API_IMAGE_NAME}
    restart: always
    ports:
      - "${API_HOST_BIND_IP:-127.0.0.1}:${API_HOST_PORT:-9090}:8080"
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_DB_CORE_JDBC_URL=jdbc:postgresql://yogieat-db:5432/yogieat
    networks:
      - yogieat-network
    env_file:
      - ${ENV_FILE_PATH:-../.env}
    depends_on:
      - yogieat-db
  yogieat-batch-sync:
    image: ${BATCH_IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_BATCH_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_DB_CORE_JDBC_URL=jdbc:postgresql://yogieat-db:5432/yogieat
      - SPRING_TASK_SCHEDULING_ENABLED=true
    networks:
      - yogieat-network
    env_file:
      - ${ENV_FILE_PATH:-../.env}
    depends_on:
      - yogieat-db
  yogieat-db:
    image: postgis/postgis:15-3.3
    container_name: yogieat-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yogieat
      POSTGRES_USER: ${DATASOURCE_DB_CORE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_DB_CORE_PASSWORD}
      TZ: Asia/Seoul
    env_file:
      - ${ENV_FILE_PATH:-../.env}
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATASOURCE_DB_CORE_USERNAME} -d yogieat" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - yogieat-network
#  TODO: Redis, etc.

networks:
  yogieat-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
