services:
  yogieat-api:
    cpus: "0.45"
    mem_limit: "384m"
    mem_reservation: "128m"

  yogieat-admin:
    cpus: "0.15"
    mem_limit: "192m"
    mem_reservation: "64m"

  yogieat-batch-sync:
    cpus: "0.10"
    mem_limit: "128m"
    mem_reservation: "64m"

  yogieat-db:
    cpus: "0.25"
    mem_limit: "256m"
    mem_reservation: "64m"
