apply plugin: 'com.google.cloud.tools.jib'

dependencies {
    implementation project(":apps:domain")
    implementation project(":storage:db-core")
    implementation project(":support:logging")
    implementation project(":external:ai")
    implementation project(":external:kakao")

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-security"

    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"

    testImplementation "org.springframework.security:spring-security-test"
}

tasks.named("bootJar") {
    enabled = true
}

tasks.named("jar") {
    enabled = false
}

def dockerHubUsername = System.getenv('DOCKERHUB_USERNAME')
def dockerHubToken = System.getenv('DOCKERHUB_TOKEN')

jib {
    from {
        image = 'amazoncorretto:25-alpine-jdk'
    }
    to {
        image = System.getenv('ADMIN_IMAGE_FULL_URL') ?: 'yogieat/yogieat-server-admin:local'
        if (dockerHubUsername && dockerHubToken) {
            auth {
                username = dockerHubUsername
                password = dockerHubToken
            }
        }
    }
    containerizingMode = 'exploded'
    container {
        mainClass = 'com.yogieat.AdminApplication'
        environment = [TZ: 'Asia/Seoul']
    }
}
