CREATE
    EXTENSION IF NOT EXISTS postgis;

CREATE
    TABLE
        t_admin(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            login_id VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            ROLE VARCHAR(255) NOT NULL,
            last_login_at TIMESTAMP(6),
            CONSTRAINT uk_admin_login_id UNIQUE(login_id)
        );

CREATE
    TABLE
        t_category(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            large_category VARCHAR(15),
            medium_category VARCHAR(255)
        );

CREATE
    TABLE
        t_region(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            code VARCHAR(30) NOT NULL,
            display_name VARCHAR(255) NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            is_active BOOLEAN NOT NULL,
            sort_order INTEGER NOT NULL,
            CONSTRAINT uk_region_code UNIQUE(code)
        );

CREATE
    TABLE
        t_gathering(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            access_key VARCHAR(255),
            title VARCHAR(255),
            scheduled_date DATE,
            time_slot VARCHAR(20),
            region_id BIGINT,
            people_count INTEGER,
            CONSTRAINT fk_gathering_region FOREIGN KEY(region_id) REFERENCES t_region(id)
        );

CREATE
    TABLE
        t_participant(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            user_id BIGINT,
            gathering_id BIGINT,
            nickname VARCHAR(8),
            distance_range VARCHAR(255),
            preferences VARCHAR(255),
            dislikes VARCHAR(255),
            ROLE VARCHAR(255)
        );

CREATE
    TABLE
        t_recommend_result(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            gathering_id BIGINT NOT NULL,
            restaurant_id BIGINT,
            agreement_rate DOUBLE PRECISION,
            status VARCHAR(255) NOT NULL,
            RANK INTEGER,
            score DOUBLE PRECISION,
            reason_text TEXT
        );

CREATE
    TABLE
        t_recommend_result_failed(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            gathering_id BIGINT NOT NULL,
            failure_reason VARCHAR(50) NOT NULL,
            error_message TEXT,
            failed_at TIMESTAMP(6) NOT NULL
        );

CREATE
    TABLE
        t_recommend_reroll_history(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            gathering_id BIGINT NOT NULL,
            excluded_restaurant_ids TEXT,
            rerolled_results TEXT
        );

CREATE
    TABLE
        t_restaurant(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            name VARCHAR(255),
            address VARCHAR(255),
            rating DOUBLE PRECISION,
            image_url VARCHAR(255),
            map_url VARCHAR(255),
            representative_review TEXT,
            description TEXT,
            region_id BIGINT,
            location geometry(
                Point,
                4326
            ),
            external_id VARCHAR(255) NOT NULL,
            category_id BIGINT,
            review_count INTEGER,
            blog_review_count INTEGER,
            represent_menu VARCHAR(255),
            represent_menu_price INTEGER,
            price_level VARCHAR(10),
            ai_mate_summary_title VARCHAR(255),
            ai_mate_summary_contents TEXT,
            time_slot VARCHAR(20),
            CONSTRAINT uk_restaurant_external_id UNIQUE(external_id),
            CONSTRAINT fk_restaurant_region FOREIGN KEY(region_id) REFERENCES t_region(id)
        );

CREATE
    TABLE
        t_restaurant_sync_job(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            SCOPE VARCHAR(20) NOT NULL,
            trigger_type VARCHAR(20) NOT NULL,
            target_restaurant_id BIGINT,
            status VARCHAR(20) NOT NULL,
            chunk_size INTEGER NOT NULL,
            parallelism INTEGER NOT NULL,
            last_processed_restaurant_id BIGINT,
            total_count BIGINT NOT NULL,
            processed_count BIGINT NOT NULL,
            success_count BIGINT NOT NULL,
            failed_count BIGINT NOT NULL,
            error_summary TEXT,
            started_at TIMESTAMP(6),
            finished_at TIMESTAMP(6)
        );

CREATE
    TABLE
        t_user(
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMP(6),
            updated_at TIMESTAMP(6),
            deleted_at TIMESTAMP(6),
            nickname VARCHAR(255),
            session_key VARCHAR(255)
        );

CREATE
    INDEX idx_admin_login_id_deleted_at ON
    t_admin(
        login_id,
        deleted_at
    );

CREATE
    UNIQUE INDEX idx_category_large_medium ON
    t_category(
        large_category,
        medium_category
    );

CREATE
    INDEX idx_region_active_sort_order ON
    t_region(
        is_active,
        sort_order
    );

CREATE
    INDEX idx_gathering_region_id ON
    t_gathering(region_id);

CREATE
    INDEX idx_gathering_region_id_deleted_at ON
    t_gathering(
        region_id,
        deleted_at
    );

CREATE
    INDEX idx_recommend_result_gathering_id ON
    t_recommend_result(gathering_id);

CREATE
    INDEX idx_recommend_result_failed_gathering_id ON
    t_recommend_result_failed(gathering_id);

CREATE
    INDEX idx_recommend_result_failed_failed_at ON
    t_recommend_result_failed(failed_at);

CREATE
    INDEX idx_recommend_reroll_history_gathering_id ON
    t_recommend_reroll_history(gathering_id);

CREATE
    INDEX idx_restaurant_name_address ON
    t_restaurant(
        name,
        address
    );

CREATE
    INDEX idx_restaurant_category_id ON
    t_restaurant(category_id);

CREATE
    INDEX idx_restaurant_deleted_at ON
    t_restaurant(deleted_at);

CREATE
    INDEX idx_restaurant_deleted_at_id ON
    t_restaurant(
        deleted_at,
        id
    );

CREATE
    INDEX idx_restaurant_region_id ON
    t_restaurant(region_id);

CREATE
    INDEX idx_restaurant_region_id_deleted_at ON
    t_restaurant(
        region_id,
        deleted_at
    );

CREATE
    INDEX idx_sync_job_status_created_at ON
    t_restaurant_sync_job(
        status,
        created_at
    );

CREATE
    INDEX idx_sync_job_trigger_created_at ON
    t_restaurant_sync_job(
        trigger_type,
        created_at
    );

CREATE
    INDEX idx_sync_job_scope_status_created_at ON
    t_restaurant_sync_job(
        SCOPE,
        status,
        created_at
    );

CREATE
    INDEX idx_sync_job_target_status_created_at ON
    t_restaurant_sync_job(
        target_restaurant_id,
        status,
        created_at
    );

CREATE
    INDEX idx_sync_job_status_started_at ON
    t_restaurant_sync_job(
        status,
        started_at
    );

INSERT
    INTO
        t_region(
            code,
            display_name,
            longitude,
            latitude,
            is_active,
            sort_order
        )
    VALUES(
        'HONGDAE',
        '홍대입구역',
        126.92378,
        37.55684,
        TRUE,
        0
    ),
    (
        'GANGNAM',
        '강남역',
        127.0276,
        37.4979,
        TRUE,
        1
    ),
    (
        'GONGDEOK',
        '공덕역',
        126.95070,
        37.54437,
        TRUE,
        2
    ),
    (
        'EULJIRO3GA',
        '을지로3가역',
        126.99224,
        37.56623,
        TRUE,
        3
    ),
    (
        'SADANG',
        '사당역',
        126.98231,
        37.47625,
        TRUE,
        4
    ),
    (
        'JONGNO3GA',
        '종로3가역',
        126.99171,
        37.57270,
        TRUE,
        5
    ),
    (
        'JAMSIL',
        '잠실역',
        127.10128,
        37.51379,
        TRUE,
        6
    ),
    (
        'SAMGAKJI',
        '삼각지역',
        126.97346,
        37.53453,
        TRUE,
        7
    );
