CREATE TABLE t_restaurant_reservation(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    restaurant_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    source VARCHAR(20) NOT NULL,
    reservation_url VARCHAR(500),
    note TEXT,
    provider_place_key VARCHAR(255),
    matched_name VARCHAR(255),
    matched_address VARCHAR(255),
    match_score DOUBLE PRECISION,
    matched_at TIMESTAMP(6),
    verified_at TIMESTAMP(6),
    rejected_at TIMESTAMP(6),
    last_checked_at TIMESTAMP(6),
    CONSTRAINT fk_restaurant_reservation_restaurant FOREIGN KEY(restaurant_id) REFERENCES t_restaurant(id)
);

CREATE INDEX idx_restaurant_reservation_restaurant_id_deleted_at
    ON t_restaurant_reservation(restaurant_id, deleted_at);

CREATE INDEX idx_restaurant_reservation_provider_status_deleted_at
    ON t_restaurant_reservation(provider, status, deleted_at);

CREATE UNIQUE INDEX uk_restaurant_reservation_restaurant_provider_active
    ON t_restaurant_reservation(restaurant_id, provider)
    WHERE deleted_at IS NULL;
